apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
      - image: https://451004051173.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone:latest
        imagePullPolicy: Always
        name: udacity-capstone
        ports:
        - containerPort: 3000
          protocol: TCP